version: '3.3'
services:
  db1:
    image: postgres:latest 
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'dev_only_pwd'
      POSTGRES_DB: 'imagery'
    volumes:
      - database_data:/var/lib/postgresql/data
  imagery:
    build:
      context: '.'
      dockerfile: 'DockerfileApp'
    ports:
      - '8080:8080'
    links:
      - db1
    environment:
      - DATABASE_URL=postgres://postgres:dev_only_pwd@db1/imagery
      - RUST_LOG=imagery_storage=debug
  lust:
    build:
      context: '.'
      dockerfile: 'DockerfileLust'
    ports:
      - '8000:8000'
    environment:
      CONFIG_FILE: '/var/lust/config.yaml'
    volumes:
      - ~/imagery_storage:/imagery_storage


volumes:
  database_data:
    driver: local
