CREATE TABLE tag (
    id UUID PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    tag_category_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tag_category_id) REFERENCES tag_category (id)
);