CREATE TABLE image (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT,
  description TEXT,
  path UUID NOT NULL UNIQUE,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
