CREATE TABLE image (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT,
  kind TEXT NOT NULL,
  path UUID NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_picture (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  image_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE
);
