CREATE TABLE referral (
  id UUID PRIMARY KEY,
  referrer_id UUID NOT NULL,
  user_id UUID NOT NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (referrer_id) REFERENCES account (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES account (id) ON DELETE CASCADE
);
